image: tmaier/docker-compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

test:
  stage: test
  tags:
    - docker
  script:
    - cd docker && docker-compose run tests


deploy:
  stage: deploy
  script:
    - echo "DEPLOY"
  when: manual