variables:
  DOCKER_DRIVER: overlay

test:
  image: tmaier/docker-compose:latest
  before_script:
    - docker info
    - docker-compose --version
  services:
    - docker:dind
  stage: test
  only:
    - pushes
  tags:
    - docker
  script:
#    - cd docker && docker-compose run tests
     - echo "test"


deploy:
  stage: deploy
  script:
    - echo "DEPLOY"
  when: manual
  only:
    - /^release/.*$/
  except:
    - branches
