version: '2'
services:
  broker:
    image: compose_broker
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - LANG=en_US.utf8

  tests:
    extends: broker
    image: broker-tests

  postgres:
    image: postgres:9.2-alpine
    container_name: compose_postgres
    environment:
      - POSTGRES_USER=dq_broker
      - POSTGRES_PASSWORD=dq_broker
      - POSTGRES_DB=dq_broker