version: '2'
services:
  app:
    container_name: master
    ports:
      - 8000:8000
    volumes:
      - ../:/usr/src/app
    links:
      - postgres

  tests:
    command: python setup.py test
    volumes:
      - ../:/usr/src/app
    links:
      - postgres

  tests-pipeline:
    extends:
      file: docker-compose.yml
      service: tests
    command: python setup.py full_test
    links:
      - postgres
