apiVersion: v1
kind: Service
metadata:
  labels:
    app: dq-broker
  name: dq-broker
spec:
  type: LoadBalancer
  loadBalancerIP: 35.205.255.205
  ports:
    - name: http
      port: 9001
      targetPort: 9001
      protocol: TCP
    - name: websocket
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: dq-broker