apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yawsm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yawsm
  template:
    metadata:
      labels:
        app: yawsm
    spec:
      containers:
        - name: yawsm
          image: gcr.io/dist-queue/yawsm:1ab74d5
          args: ["yawsm", "-c", "env.cfg"]
          ports:
          - containerPort: 9000
            name: websocket
          - containerPort: 9001
            name: http
          env:
            - name: LANG
              value: en_US.utf8
            - name: YAWSM_DATABASE_HOSTNAME
              value: postgres
            - name: YAWSM_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: db
            - name: YAWSM_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: YAWSM_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: YAWSM_WEBSOCKET_PING_INTERVAL
              value: "10"
            - name: YAWSM_WEBSOCKET_PING_TIMEOUT
              value: "10"
            - name: YAWSM_DEFAULT_ADMIN_USERNAME
              value: admin